# Generated by Django 5.2.3 on 2025-06-20 21:51

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='about',
            field=markdownx.models.MarkdownxField(blank=True),
        ),
    ]
