# Generated by Django 5.2.3 on 2025-06-20 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_siteconfig_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='about',
            field=models.TextField(blank=True),
        ),
    ]
